Checklist/Avaliacao/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^categoria/$', views.categoria, name = 'categoria'),
	url(r'^questao/$', views.questao, name = 'questao'),
	url(r'^checklist/$', views.checklist, name = 'checklist'),
	url(r'^avaliacao/$', views.avaliacao, name = 'avaliacao'),
	url(r'^respCheck/(?P<pk>[0-9]+)/$', views.respCheck, name = 'respCheck'),
	url(r'^avaliacao_list/$', views.avaliacao_list, name = 'avaliacao_list'),
	url(r'^config/$', views.config, name = 'config'),
	url(r'^checklist_list/$', views.checklist_list, name = 'checklist_list'),
	url(r'^relatorio/(?P<pk>[0-9]+)/$', views.relatorio, name = 'relatorio'),
]

Checklist/Checklist/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Usuario import views
from Sistema import views
from Avaliacao import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^', include('Usuario.urls', namespace='Usuario', app_name='Usuario')),
    url(r'^', include('Sistema.urls', namespace='Sistema', app_name='Sistema')),
    url(r'^', include('Avaliacao.urls', namespace='Avaliacao', app_name='Avaliacao'))
]

Checklist/Sistema/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cadastroSistema/$', views.cadastroSistema, name = 'cadastroSistema'),
    url(r'^sistema_list/$', views.sistema_list, name = 'sistema_list'),
]

Checklist/Avaliacao/models.py
from __future__ import unicode_literals
from django.db import models
from django.template.defaultfilters import default
from Usuario.models import Usuario
from Sistema.models import Sistema
# Create your models here.

class Categoria(models.Model):
	nome = models.CharField(
		max_length=150, null = False, unique=True
	)
	descricao = models.CharField(
		max_length=180, null = False
	)

class Questoes(models.Model):
	questao = models.CharField(
		max_length = 255, null = False
	)
	Categoria = models.ForeignKey(Categoria)
	diretrizes = models.CharField(
		max_length = 255, null = True
	)

class Checklist(models.Model):
	nome = models.CharField(
		max_length = 80, null=False, unique=True
	)
	descricao = models.CharField(
		max_length = 255, null= True
	)
	especialista = models.ForeignKey(Usuario)	
	categoria = models.ManyToManyField(Categoria, through='Checklist_Categoria')

class Checklist_Categoria(models.Model):
	checklist = models.ForeignKey(Checklist)
	categoria = models.ForeignKey(Categoria)

class Avaliacao(models.Model):
	sistema = models.ForeignKey(Sistema)
	nome = models.CharField(max_length = 80, null =False)
	responsavel = models.ManyToManyField(Usuario, through='Avaliacao_Responsavel')
	plataforma = models.CharField(max_length = 80, null=False)
	checklist = models.ForeignKey(Checklist)

class Avaliacao_Responsavel(models.Model):
	avaliacao = models.ForeignKey(Avaliacao)
	responsavel = models.ForeignKey(Usuario)

class Resposta(models.Model):
	questao = models.ForeignKey(Questoes)
	resposta = models.CharField(max_length = 3, null= False)
	avaliacao = models.ForeignKey(Avaliacao)
	checklist = models.ForeignKey(Checklist)

Checklist/Avaliacao/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from Avaliacao.models import Categoria, Questoes, Checklist, Avaliacao, Resposta
from Usuario.models import Usuario
from Sistema.models import Sistema
from django.db.transaction import commit

class CategoriaModelForm(forms.ModelForm):
	Categoria._meta.get_field('nome').blank = False
	Categoria._meta.get_field('descricao').blank = False
	class Meta:
		model = Categoria
		fields = ['nome', 'descricao']
		widgets = {
			'nome' : forms.TextInput(attrs={'class': 'form-control', 'maxlength': 150, 'placeholder': 'Nome'}),
			'descricao' : forms.TextInput(attrs={'class': 'form-control', 'maxlength': 180, 'placeholder': 'Descrição'})
		}
	
	def save(self, commit=True):
		Categoria = super(CategoriaModelForm, self).save(commit=False)
		if commit:
			Categoria.save()
		return Categoria

class QuestaoModelForm(forms.ModelForm):
	Questoes._meta.get_field('questao').blank = False
	Questoes._meta.get_field('diretrizes').blank = False
	Questoes._meta.get_field('Categoria').blank = False
	class Meta:
		model = Questoes
		fields = ['questao', 'diretrizes', 'Categoria']
		choice = [(cat.pk, cat.nome) for cat in Categoria.objects.all()]
		widgets = {		
            'questao' : forms.TextInput(attrs={'class' : 'form-control', 'maxlength': 255, 'placeholder': 'Questão'}),
            'diretrizes' : forms.TextInput(attrs={'class' : 'form-control', 'maxlength': 255, 'placeholder': 'Diretrizes'}),
            'Categoria': forms.Select(attrs={'class' : 'form-control', 'maxlength': 255, 'placeholder': 'Categoria'},choices=choice),             
        	     
		}

	def save(self, commit=True):
		Questao = super(QuestaoModelForm, self).save(commit=False)
		if commit:
			Questao.save()
		return Questao
		
class ChecklistModelForm(forms.ModelForm):
	Checklist._meta.get_field('nome').blank = False
	Checklist._meta.get_field('descricao').blank = False
	Checklist._meta.get_field('especialista').blank = False
	Checklist._meta.get_field('categoria').blank = False
	class Meta:
		model = Checklist
		fields = ['nome', 'descricao', 'especialista', 'categoria']
		choice = [(elab.pk, elab) for elab in Usuario.objects.filter(categoria='ESPECIALISTA')]
		options = [(cat.pk, cat.nome) for cat in Categoria.objects.all()]
		widgets = {
			'nome' : forms.TextInput(attrs={'class' : 'form-control', 'maxlength': 255, 'placeholder': 'Nome'}),
			'descricao' : forms.TextInput(attrs={'class' : 'form-control', 'maxlength': 255, 'placeholder': 'Descrição'}),
			'especialista' : forms.Select(attrs={'class' : 'form-control', 'maxlength': 255, 'placeholder': 'Especialista'},choices=choice),
			'categoria' : forms.CheckboxSelectMultiple(choices=options),		}

	def save(self, commit=True):
		Checklist = super(ChecklistModelForm, self).save(commit=False)
		if commit:
			Checklist.save()
		return Checklist

class AvaliacaoModelForm(forms.ModelForm):
	Avaliacao._meta.get_field('sistema').blank = False
	Avaliacao._meta.get_field('responsavel').blank = False
	Avaliacao._meta.get_field('plataforma').blank = False
	Avaliacao._meta.get_field('checklist').blank = False
	class Meta:
		model = Avaliacao	
		fields = ['sistema', 'responsavel', 'plataforma', 'checklist', 'nome']
		choiceSis = [(sis.pk, sis) for sis in Sistema.objects.all()]
		choiceResp = [(resp.pk, resp) for resp in Usuario.objects.filter(categoria='AVALIADOR')]
		choiceChk = [(chk.pk, chk) for chk in Checklist.objects.all()]
		widgets = {
			'sistema' : forms.Select(attrs={'class' : 'form-control', 'maxlength': 255, 'placeholder': 'Sistema'},choices=choiceSis),
			'responsavel' : forms.CheckboxSelectMultiple(choices=choiceResp),
			'plataforma' : forms.TextInput(attrs={'class' : 'form-control', 'maxlength': 80, 'placeholder': 'Plataforma'}),
			'checklist' : forms.Select(attrs={'class' : 'form-control', 'maxlength': 255, 'placeholder': 'Checklist'},choices=choiceChk),
			'nome' : forms.TextInput(attrs={'class' : 'form-control', 'maxlength': 80, 'placeholder': 'Nome'})
		}

	def save(self, commit=True):
		Avaliacao = super(AvaliacaoModelForm, self).save(commit=False)
		if commit:
			Avaliacao.save()
		return Avaliacao


class RespostaModelForm(forms.ModelForm):
	Resposta._meta.get_field('resposta').blank = False
	class Meta:
		model = Resposta
		fields = ['resposta']
		choice = (('Sim', 'Sim'), ('Nao', 'Nao'), ('N/A', 'N/A'))
		widgets = {
			'resposta' : forms.RadioSelect(choices=choice)
		}

Checklist/Avaliacao/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, render, redirect
from django.contrib.auth.forms import UserCreationForm
from Avaliacao.models import Categoria, Questoes, Checklist, Checklist_Categoria, Avaliacao, Avaliacao_Responsavel, Resposta
from Avaliacao.forms import CategoriaModelForm, QuestaoModelForm, ChecklistModelForm, AvaliacaoModelForm, RespostaModelForm
from Sistema.models import Sistema
from django.contrib import messages
from django.views.generic import ListView

def categoria(request):
	form = CategoriaModelForm(request.POST or None)
	context = {'form': form}
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			messages.success(request, 'Categoria cadastrada')
			return redirect('/config')

	return render(request, 'Avaliacao/categoria.html', context)


def questao(request):
	form = QuestaoModelForm(request.POST or None)
	form.fields['Categoria'].choices = [(cat.pk, cat.nome) for cat in Categoria.objects.all()]
	if request.method == 'POST':
		if form.is_valid():	
			form.save()
			messages.success(request, 'Questao cadastrada')
			return redirect('/config')

	return render(request, 'Avaliacao/questao.html', {'form': form})

	
def checklist(request):
	form = ChecklistModelForm(request.POST or None)
	form.fields['categoria'].choices = [(cat.pk, cat.nome) for cat in Categoria.objects.all()]	
	if request.method == 'POST':
		if form.is_valid():
			print('valido')
			checklist = form.save()
			for cat in form.fields['categoria'].queryset:
				ChkCat = Checklist_Categoria.objects.create(categoria_id = cat.pk, checklist_id= checklist.pk)
				ChkCat.save()
			messages.success(request, 'Checklist cadastrado')
		return redirect('/config')
	return render(request, 'Avaliacao/checklist.html', {'form': form})

def avaliacao(request):
	form = AvaliacaoModelForm(request.POST or None)
	form.fields['sistema'].choices = [(sis.pk, sis.nome) for sis in Sistema.objects.all()]
	form.fields['checklist'].choices = [(chk.pk, chk.nome) for chk in Checklist.objects.all()]	
	if request.method == 'POST':
		if form.is_valid():
			avaliacao = form.save()
			for resp in form.fields['responsavel'].queryset:
				responsavel = Avaliacao_Responsavel.objects.create(avaliacao_id = avaliacao.pk, responsavel_id = resp.pk)
				responsavel.save()
			messages.success(request, 'Avaliação cadastrada')
		return redirect('/config')
	return render(request, 'Avaliacao/avaliacao.html', {'form':form})


def respCheck(request, pk):
	avaliacao = Avaliacao.objects.get(pk=pk)
	chk_id = avaliacao.checklist_id
	chkcat = Checklist_Categoria.objects.filter(checklist_id=chk_id)
	categoria = Categoria.objects.all()	
	questaoForm = []
	for obj in chkcat:
		questlist = Questoes.objects.filter(Categoria_id= obj.categoria_id)
		for questao in questlist:
			questaoForm.append(questao)
	respostaForm = RespostaModelForm(request.POST or None)
	if request.method == 'POST':
			if respostaForm.is_valid():
				for questao in questaoForm:
					resp = request.POST.get('resposta')
					resposta = Resposta.objects.create(avaliacao_id= avaliacao.pk, checklist_id=chk_id, questao_id = questao.id, resposta=resp)
					resposta.save()		
			return redirect('/config')
	return render(request, 'Avaliacao/respCheck.html', {'form': questaoForm, 'formResp': respostaForm, 'pk': pk, 'categoria':categoria})




def avaliacao_list(request):
	form = Avaliacao.objects.all()
	return render(request, 'Avaliacao/avaliacao_list.html', {'form': form})


def config(request):	
    return render(request, 'retorno.html')

def checklist_list(request):
	return render(request, 'Avaliacao/checklist_list.html')

def relatorio(request, pk):
	avalist = Avaliacao.objects.filter(sistema_id=pk)
	questoes = []
	sim = 0
	nao = 0
	total = 0
	for avaliacao in avalist:
		catChk = Checklist_Categoria.objects.filter(checklist_id=avaliacao.checklist_id)
		for obj in catChk:
			questlist = Questoes.objects.filter(Categoria_id=obj.categoria_id).order_by()
			for questao in questlist:
				categoria = Categoria.objects.get(pk=obj.categoria_id)
				resposta = Resposta.objects.filter(questao_id=questao.pk)
				for resp in resposta:
					if resp.resposta == 'Sim':
						sim = sim + 1
					elif resp.resposta == 'Nao':
						nao = nao + 1
					total = total + 1
			na = total - (sim + nao)
			sim = (sim * 100)/total	
			nao = (nao * 100)/total
			questoes.append({'categoria': categoria.nome, 'sim': sim, 'nao': nao, 'na': na, 'avaliacao':avalist})
			sim = nao = total = 0
	return render(request, 'Avaliacao/relatorio.html', {'questoes':questoes, 'pk': pk})

Checklist/templates/Avaliacao/avaliacao.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'Avaliacao:avaliacao' %}" class="form-signin" method="post">
{% csrf_token %}
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Cadastro de Avaliação </p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        {{form.nome}}
                            <p class="help-block text-danger"></p>     
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        {{form.sistema}}
                            <p class="help-block text-danger"></p>     
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        {{form.checklist}}
                            <p class="help-block text-danger"></p>     
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            {{ form.plataforma}}
                            <p class="help-block text-danger"></p>     
                        </div>
                    </div>
                    <div class="row control-group">
                        <!--div class="form-group col-xs-12 floating-label-form-group controls"-->
                        <h5>Selecione os responsaveis por responder a avaliação</h5>
                            <h5>{{ form.responsavel}}</h5>
                            <p class="help-block text-danger"></p>                        
                        <!--/div-->
                    </div>                               
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Cadastrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

  <hr>
</form>

{% endblock %}

Checklist/templates/Avaliacao/avaliacao_list.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'Avaliacao:avaliacao_list' %}" class="form-signin" method="post">
{% csrf_token %}
    <div class="post-preview">
        <h2 class="post-title">
          Aqui todas as avaliações de Checklist cadastradas
        </h2>
         <p class="post-meta">Clique no nome para Avaliar</p>
         <p>inserir uma <a href="{% url 'Avaliacao:avaliacao' %}">nova Avaliação?</a></p>
    </div>
    <hr>


 		{% for avaliacao in form %}
        <div class="post-preview">
 			<div class="post-preview">
    			<h4 class="post-title">
 				<p class="post-title"><a href="{% url 'Avaliacao:respCheck' avaliacao.pk %}">
                {{ avaliacao.nome }}</a></p>
 				</h4>
 				<!--p class="post-meta"> <a href="{% url 'Avaliacao:avaliacao_list' %}">Editar</a></p-->
 				<!--p class="post-meta"><a href="{% url 'Avaliacao:respCheck' avaliacao.pk %}">Avaliar</a></p-->
    	<hr>
 			</div>
 		</div>
 <!-- Pager -->
	<!--div class="row">
    	<div class="form-group col-xs-12">
        	<h1 align="left"><button type="submit" class="btn btn-default" href="#">Editar</button></h1>
        </div>
     </div>
    <div class="row">
        <div class="form-group col-xs-12">
            <h1 align="left"><button type="submit" class="btn btn-default" href="#">relatorio</button></h1>
         </div>
     </div-->
{% endfor %}
{% endblock %}

Checklist/templates/Avaliacao/categoria.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'Avaliacao:categoria' %}" class="form-signin" method="post">
{% csrf_token %}
<h2 class="form-signin-heading">Categoria de Questoes</h2>
{{ form.nome}}
{{ form.descricao }}

<button class="btn btn-lg btn-primary btn-block" type="submit">Cadastrar</button>
</form>

{% endblock %}

Checklist/templates/Avaliacao/checklist.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'Avaliacao:checklist' %}" class="form-signin" method="post">
{% csrf_token %}
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Cadastro de Checklist </p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        {{form.nome}}
                            <p class="help-block text-danger"></p>     
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        {{form.descricao}}
                            <p class="help-block text-danger"></p>     
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            {{ form.especialista}}
                            <p class="help-block text-danger"></p>     
                        </div>
                    </div>
                    <div class="row control-group">
                        <!--div class="form-group col-xs-12 floating-label-form-group controls"-->
                        <h5>Selecione as categorias que vão compor o Checklist</h5>
                            <h5>{{ form.categoria}}</h5>                       
                        <!--/div-->
                    </div>                                            
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Cadastrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

  <hr>
</form>

{% endblock %}

Checklist/templates/Avaliacao/checklist_list.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'Avaliacao:avaliacao_list' %}" class="form-signin" method="post">
{% csrf_token %}
 <div class="post-preview">
        <h3 class="post-title">
          Crie aqui as Categorias
        </h3>
         <p>Deseja inserir uma  <a href="{% url 'Avaliacao:categoria' %}">nova Categoria?</a></p>
    </div>
    <hr>
    <div class="post-preview">
        <h3 class="post-title">
          Crie aqui o seu Checklist
        </h3>
         <p>Deseja inserir um  <a href="{% url 'Avaliacao:checklist' %}">novo Checklist?</a></p>
    </div>
    <hr>
    <div class="post-preview">
        <h3 class="post-title">
          Crie aqui as Questões
        </h3>
         <p>Deseja inserir uma  <a href="{% url 'Avaliacao:questao' %}">nova Questão?</a></p>
    </div>
    <hr>

{% endblock %}

Checklist/templates/Avaliacao/questao.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'Avaliacao:questao' %}" class="form-signin" method="post">
{% csrf_token %}
<div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Cadastro de Questões </p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        {{form.questao}}
                            <p class="help-block text-danger"></p>     
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        {{form.diretrizes}}
                            <p class="help-block text-danger"></p>     
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            {{ form.Categoria}}
                            <p class="help-block text-danger"></p>                        
                        </div>
                    </div>                           
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Cadastrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

  <hr>
</form>

{% endblock %}

Checklist/templates/Avaliacao/relatorio.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'Avaliacao:relatorio' pk %}" class="form-signin" method="post">
{% csrf_token %}
<div class="post-preview">
    <h3 class="post-title">
        Relatório 
    </h3>  
    <hr> 
</div>  
	{% for questao in questoes %}
<h4 class="post-subtitle">{{questao.categoria}}</h4>
    	<p> Sim: {{questao.sim}}%</p>
    	<p> Não: {{questao.nao}}% </p>
    	<p> Não se Aplica: {{questao.na}}</p>
    	</h5>
    <hr>
    	{% endfor %}
    <!--/div-->
</form>
</form>

{% endblock %}

Checklist/templates/Avaliacao/respCheck.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'Avaliacao:respCheck' pk %}" class="form-signin" method="post">
{% csrf_token %}
<div class="row">
 	<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
         <p>Checklist</p>
{% for questao in form %}
<form name="sentMessage" id="contactForm" novalidate>
    <div class="row control-group">
        {{ questao.questao }}
		{{ formResp.resposta }}
        <p class="help-block text-danger"></p> 
    </div>
  <hr>
{% endfor %}
<br>
  	<div id="success"></div>
        <div class="row">
          <div class="form-group col-xs-12">
            <button type="submit" class="btn btn-default">Finalizar</button>
           </div>
        </div>
</form>
</form>

{% endblock %}