Checklist/Avaliacao/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^categoria/$', views.categoria, name = 'categoria'),
	url(r'^questao/$', views.questao, name = 'questao'),
	url(r'^checklist/$', views.checklist, name = 'checklist'),
	url(r'^avaliacao/$', views.avaliacao, name = 'avaliacao'),
	url(r'^respCheck/(?P<pk>[0-9]+)/$', views.respCheck, name = 'respCheck'),
	url(r'^avaliacao_list/$', views.avaliacao_list, name = 'avaliacao_list'),
	url(r'^config/$', views.config, name = 'config'),
	url(r'^checklist_list/$', views.checklist_list, name = 'checklist_list'),
	url(r'^relatorio/(?P<pk>[0-9]+)/$', views.relatorio, name = 'relatorio'),
]

Checklist/Checklist/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Usuario import views
from Sistema import views
from Avaliacao import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^', include('Usuario.urls', namespace='Usuario', app_name='Usuario')),
    url(r'^', include('Sistema.urls', namespace='Sistema', app_name='Sistema')),
    url(r'^', include('Avaliacao.urls', namespace='Avaliacao', app_name='Avaliacao'))
]

Checklist/Sistema/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cadastroSistema/$', views.cadastroSistema, name = 'cadastroSistema'),
    url(r'^sistema_list/$', views.sistema_list, name = 'sistema_list'),
]

Checklist/Usuario/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name = 'index'),
    url(r'^cadastro/$', views.cadastro, name = 'cadastro'),
]

Checklist/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Test Usability</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'bootstrap/css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'bootstrap/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'Usuario:index' %}">Home</a>
                <a class="navbar-brand" href="{% url 'Usuario:cadastro' %}">Cadastre-se</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'Avaliacao:avaliacao_list' %}">Avaliação</a>
                    </li>
                    <!--li>
                        <a href="{% url 'Avaliacao:categoria' %}">Categoria</a>
                    </li-->
                    <li>
                        <a href="{% url 'Avaliacao:checklist_list' %}">Checklist</a>
                    </li>
                    <!--li>
                        <a href="{% url 'Avaliacao:questao' %}">Questões</a>
                    </li-->
                    <li>
                        <a href="{% url 'Sistema:sistema_list' %}">Sistema</a>
                    </li>
                    <!--li>
                        <a href="{% url 'Usuario:cadastro' %}">Usuario</a>
                    </li-->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Test Usability</h1>
                        <hr class="small">
                        <span class="subheading">Uma ferramenta para inspeção por checklist</span>
                    </div>
                </div>
            </div>
        </div>
    </header>


<!-- Main Content -->

    <div class="container">

    {% block content %}
   
    {% endblock %}


    </div> <!-- /container -->



    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <!--li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li-->
                        <li>
                            <a href="https://github.com/rayannelana14/ProjetoTcc">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Test Usability 2017</p>
                </div>
            </div>
        </div>
    </footer>


    <!-- jQuery -->
    <script src="{% static 'bootstrap/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'bootstrap/js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'bootstrap/js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'bootstrap/js/clean-blog.min.js' %}"></script>


</body>

</html>

Checklist/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Checklist</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'jumbotron/jumbotron.css' %}" rel="stylesheet">

    <link href="{% static 'bootstrap/css/dropdown.css' %}" rel="stylesheet">

    <link href="{% static 'bootstrap/js/bootstrap.min.js' %}" rel="stylesheet">

    <link href="{% static 'bootstrap/js/dropdown.js' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Inspeção por Checklist</a>
        </div>
        <!--div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Senha" class="form-control">
            </div>
            <button type="Entrar" class="btn btn-primary" href="{% url 'Usuario:config' %}">Entrar</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
    

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Sobre</h1>
        <p>Essa ferramenta foi desenvolvida na disciplina de Trabalho de Conclusão de Curso na PUC Minas como requisito parcial para obtenção do título de bacharel de Sistemas de informação e propoem-se auxiliar na avaliação preditiva de interfaces, fornecendo um ambiente onde é possivél criar e responder checklists.
        Este trabalho tem como propósito apoiar o processo de desenvolvimento de software, auxiliando na identificação de erros de usabilidade da interface. 
        </p>
        <!--p><a class="btn btn-primary btn-lg" href="{% url 'Usuario:cadastro' %}" role="button">Cadastre-se &raquo;</a></p-->
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <!--h2>Usuário</h2>
          <p></p-->
          <p><a class="btn btn-default" href="{% url 'Usuario:cadastro' %}" role="button">Usuario &raquo;</a></p>
        </div>
        <div class="row">
          <div class="col-md-4">            
            <!--h2>Cadastre-se</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p-->
            <p><a class="btn btn-default" href="{% url 'Sistema:cadastroSistema' %}" role="button">Sistema &raquo;</a></p>
        </div>
        <!--div class="col-md-4">
          <!--h2>Checklist</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p-->
          <!--p><a class="btn btn-default" href="#" role="button">Checklist &raquo;</a></p>
        </div>
      </div>
    
      <!--Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <!--h2>Cadastre-se</h2>
          <p>Para utilizar nossa ferramenta, cadastre-se. </p-->
          <p><a class="btn btn-default" href="{% url 'Avaliacao:checkindex' %}" role="button">Checklist &raquo;</a></p>
        </div>        
      <hr>
    
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
   
  </body>
</html>

Checklist/templates/retorno.html
{% extends 'base.html' %}
{% block content %}
<script>
    alert('Dados salvos com sucesso');
	window.location="http://127.0.0.1:8000";  
</script>
{% endblock %}